pipeline {

    agent any
     environment {
       DOCKER = 'C:/Users/DELL/AppData/Local/Programs/DockerDesktop/resources/bin/docker.exe'
       IMAGE_NAME = 'jenkins-demo-app'
}

    parameters {
        string(
            name:'APP_PORT',
            defaultValue:'3000',
            description:'Server Port'
        )
    }
    environment{
        IMAGE_NAME='jenkins-demo-app'
    }
    stages{
        stage('Checkout'){
            steps{
                echo 'Checking out source code from Git Repo'
                checkout scm
            }
        }
        stage('Check Docker'){
            steps{
                bat '"%DOCKER%" --version'
            }
        }
        stage('Dependencies'){
            steps{
                bat 'npm install'
            }
        }
        stage('Test APP'){
            steps{
              bat 'npm test'
            }
        }
        stage('Build'){
            steps{
              bat '"%DOCKER%" build -t %IMAGE_NAME%:%BUILD_NUMBER% .'

            }
        }
        stage('Run Container'){
            steps{
              bat '''
                "%DOCKER%" run -d --name node-app-%BUILD_NUMBER% -p %APP_PORT%:3000 %IMAGE_NAME%:%BUILD_NUMBER%
              '''

            }

        }
        stage('Verify'){
            steps{
              bat '''
                 echo APP Deployed Successfully
                 echo Open http://localhost:%APP_PORT%
                 "%DOCKER%" ps
              '''  


            }
        }

    }
}